### ISSUE TITLE
Website link in Github Front Page

### ISSUE THREAD

**Issue by JauntyJJS** [MeikeSteinhilber/spirit#5]
Hi,

Is it possible to update this link  from [meike-steinhilber.shinyapps.io/sprtt/](https://meike-steinhilber.shinyapps.io/sprtt/) to [https://meike-steinhilber.shinyapps.io/spirit/](https://meike-steinhilber.shinyapps.io/spirit/) instead ?

![image](https://user-images.githubusercontent.com/9066508/175802118-14d974cd-f6e6-42b2-b56c-828ed2280622.png)

Thank you.

**Comment by MeikeSteinhilber** [comment]
Thanks for the comment! I fixed it 😄
